name: stability_ai
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/aq1018/stability_ai_dart

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  fixnum: ^1.0.1
  grpc: ^3.1.0
  protobuf: ^2.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

